num = str(input('Digite um numero entre 0 e 9999 utiizando 4 digitos: '))
print('Unidade: ',num[3:4: ],)
print('Dezena: ',num[ 2:3: ],)
print('Centena: ',num[1:2: ],)
print('Milhar: ',num[ :1: ],)
